### ISSUE TITLE
Error in whitelist-html.php causes 3.9 version to crash

### ISSUE THREAD

**Issue by gjrdiesel** [xibodevelopment/backupwordpress#1206]
# The problem (severity: Urgent)
Latest version is seeing an error like the following:
```
Warning: require_once(/home/xxx/public_html/wp-content/plugins/backupwordpress/whitelist-html/whitelist-html.php): failed to open stream: No such file or directory in /home/xxx/public_html/wp-content/plugins/backupwordpress/classes/class-plugin.php on line 133

Fatal error: require_once(): Failed opening required '/home/xxx/public_html/wp-content/plugins/backupwordpress/whitelist-html/whitelist-html.php' (include_path='.:/opt/cpanel/ea-php70/root/usr/share/pear') in /home/xxx/public_html/wp-content/plugins/backupwordpress/classes/class-plugin.php on line 133
```
![image](https://user-images.githubusercontent.com/3363867/59236709-5f961400-8bc5-11e9-8445-81d0a55c1972.png)

The fatal error is causing the entire wordpress installation to crash as reported numerous times here: https://wordpress.org/support/plugin/backupwordpress/

## Temporary solution

If you can FTP or SSH to your website, rename the `backupwordpress` folder found in `wp-content/plugins/` to something else like `broken_backupwordpress` temporarily disable the plugin until the author has released a new fix.

Or WordPress since version 5.2 should send you a email with a login token to your site administrator email address that will let you login in recovery mode and possibly disable the plugin (I haven't been able to test this method personally)

You can also download the previous version straight from wordpress.org: https://downloads.wordpress.org/plugin/backupwordpress.3.8.zip

You can also follow the instructions here for another alternative way to fix the plugin by merging it with an older version https://wordpress.org/support/topic/how-i-fixed-3-9-crash/

## Potential long term fixes

https://github.com/xibodevelopment/backupwordpress/blob/291581972394e0d8107713488ebb0f7728f945fe/.gitmodules#L6

Looks looks like the last release didn't bring in the whitelist-html git submodule because https://github.com/xibodevelopment/whitelist-html.git doesn't exist. 

Correct repository looks like it should be https://github.com/humanmade/whitelist-html

### Testing
It would be great to set up the `travis.yml` file and travis.org testing prevent future issues.

-- Updated because this page is seeing being linked a lot from the official WordPress.org support forum.

**Comment by neko** [comment]
I'm baffled as to how it's gone 15 hours without being resolved. Was the release done in a rush before heading home for the day or something?

I'm keen to know what will be done in regards to plugin maintenance, this broken update was the first in 7 months and it was literally to just remove the XIBO support email from the plugin, instead linking to the WordPress support forums that have not had a XIBO reply for 6 months.

From the looks of it, XIBO has also been hastily removed from the footer of the UpdraftPlus website (it's still in the html, just for some reason has been removed via jquery):
![image](https://user-images.githubusercontent.com/6992756/59245618-af71eb00-8c58-11e9-8c55-2d620b23cf5a.png)
![image](https://user-images.githubusercontent.com/6992756/59245641-c0226100-8c58-11e9-86bf-417b65a65e86.png)

Is XIBO now defunct? Will maintenance be handed over to someone else?

**Comment by pmleconte** [comment]
Hi,
It seems that 2 directories are empty/missing in current release : backdrop and whitelist-html.
To make this plugin work, I had to copy their contents from previous release.
Just hope this help you while waiting for an official fix.
Pascal

**Comment by JonasToth** [comment]
Having the problem as well, temporarily disabled the plugin through recovery in wordpress 5.2.

**Comment by darthvader666uk** [comment]
I have updated Master and tagged a release:

https://github.com/xibodevelopment/backupwordpress/releases/tag/3.10

It has been updated to WP.Org and have tested it locally on WP 5.1.

let me know how that goes.

[3.10.zip](https://github.com/xibodevelopment/backupwordpress/files/3280022/3.10.zip)

**Comment by Jamesking56** [comment]
@darthvader666uk seems to work for me :+!:

**Comment by JonasToth** [comment]
looks good to me as well, thanks for your fast fix!

**Comment by pmleconte** [comment]
Ok for me too, thank you
