### ISSUE TITLE
Only catch PHP errors from backupwordpress

### ISSUE THREAD

**Issue by willmot** [xibodevelopment/backupwordpress#228]
```
Fatal error: Out of memory (allocated 50069504) (tried to allocate 2097145 bytes) in /homepages/30/d252473173/htdocs/wp-content/plugins/backupwordpress/classes/schedule.php on line 648
```

**Comment by willmot** [comment]
Should do as part of https://github.com/humanmade/backupwordpress/issues/608

**Comment by libby-barker** [comment]
@willmot can you confirm if this was resolved in #608 or if it is still open?

**Comment by willmot** [comment]
#608 is still open...

Both this and that issue are still valid and haven't been started.

**Comment by katmoody** [comment]
@willmot - quick question for you. I see in #231 a full list of error messages and what they represent - are those all still valid even if the error message isn't fully updated in the admin? 

I'm trying to pin down this one that's been showing up in a few tickets, specifically: 

```Errcode 122: Mysqldump: mysqldump: Can't create/write to file ```

When searching online I see a few different things this could mean, including running out of disk space and improper permissions on the directory/file. When the backup fails even though our support module shows they have everything installed function and command-wise, that would indicate it's running out of space, right? 

I'm wanting to be sure as they have a lot of disabled functions with custom prefixes, so I'd like to know whether those could have any bearing on whether they can fix this by asking their host to check their disk quota? Those are: 

```pcntl_alarm,pcntl_fork,pcntl_waitpid,pcntl_wait,pcntl_wifexited,pcntl_wifstopped,pcntl_wifsignaled,pcntl_wexitstatus,pcntl_wtermsig,pcntl_wstopsig,pcntl_signal,pcntl_signal_dispatch,pcntl_get_last_error,pcntl_strerror,pcntl_sigprocmask,pcntl_sigwaitinfo,pcntl_sigtimedwait,pcntl_exec,pcntl_getpriority,pcntl_setpriority,```

**Comment by willmot** [comment]
> When the backup fails even though our support module shows they have everything installed function and command-wise, that would indicate it's running out of space, right?

It could be either lack of space or a permissions issue (or some other issue that's preventing file writing for whatever reason), It's not something our support module checks would catch necessarily. I'd recommend they try reaching out to their host to see if they can help identify the issue.

The plugin should still fall-back to the PHP Mysqldump implementation which might then not be affected by whatever is causing the issue, do you know whether that is happening? Or are database backups completely failing?

**Comment by katmoody** [comment]
Hey there @willmot - in their case the database backups are completely failing. Which makes me think more that it's a lack of space since I don't know that permissions would affect the database?
