### ISSUE TITLE
Backup progress

### ISSUE THREAD

**Issue by willmot** [xibodevelopment/backupwordpress#28]
Can we even track progress?

**Comment by pdewouters** [comment]
Actually, I will use ProcessBuilder http://symfony.com/doc/current/components/process.html

**Comment by willmot** [comment]
Since switching to `Process` in #1001 we can now get access to progress: http://symfony.com/doc/current/components/process.html#getting-real-time-process-output

**Comment by libby-barker** [comment]
@willmot and @pdewouters is this issue still active following merge of #1001 ? If so, what are the actionable tasks here?

**Comment by willmot** [comment]
Yep still an issue. We don't present meaningful progress to the user currently, just a spinner and basic  status message (backing up files etc).

Ideally we'd show more detailed progress so that users can see how long the backup is expected to take and how far through the process currently is.
