### ISSUE TITLE
Ability to look inside the zip file. 

### ISSUE THREAD

**Issue by willmot** [xibodevelopment/backupwordpress#44]
As a user I should be able to view additional details about a backup including the ability to browse the files inside the zip.

- [ ] Add a new "Details" link to the action links shown alongside each backup in the backups table.
- [ ] Clicking that takes you to a new page or shows a panel with the new information
- [ ] We then display more detailed information about the backup including
    - Backup date
    - Version of WordPress
    - If the backup contains a database then show a panel with information about the database. Size, number of posts, users etc.
    - If the backup contains files then show a panel with information about the files. Number of files, total size, etc. Along with the ability to browse the file list (in an interface similar to the file list in the excludes settings pane).

This would be useful for users who want to quickly check if a backup contains a specific file / folder or a version of such.

With this as a base we could then further enhance in the future:

- Ability to download/view individual files.
- Ability to restore an individual file / folder right from the detail page.
- Additional meta information about the site that the backup contains (active theme, etc)

**Comment by libby-barker** [comment]
@willmot can we close this issue as it sounds like #632 resolves?

**Comment by willmot** [comment]
Had hoped #632 would make this possible, doesn't actually implement this feature. Unfortunately Finder doesn't support browsing Zip files.

I've updated the description with more detail / scope.
