### ISSUE TITLE
Document how to run our unit tests locally

### ISSUE THREAD

**Issue by willmot** [xibodevelopment/backupwordpress#837]
Developers should be running unit tests locally before submitting changes, we need to document how they can do that. The wiki would be a good place to start.

**Comment by willmot** [comment]
Also document how to run them on windows (or at least link to it).

**Comment by willmot** [comment]
@dashaluna fancy documenting this alongside getting them running locally?

**Comment by dashaluna** [comment]
@willmot I need to do that.. so will start writing things down when I get to it. However, it will be for mac :) Will need some help with windows, will ask others.
