### ISSUE TITLE
Host support matrix

### ISSUE THREAD

**Issue by willmot** [xibodevelopment/backupwordpress#838]
We should start tracking whether BackUpWordPress works across the many hosts and hosting plans. This can be crowd sourced and is a great way for non-developers to help out as they can manually test the plugin on any hosting accounts they have access too.

We need:
1. A spreadsheet which can be community edited that tracks:
   - Host
   - Hosting plan
   - Details about the hosting environment
   - Does the plugin work 100%
   - Core functionality works but there are non-breaking issues
   - Core functionality doesn't work
   - Do we have a contact at the host
   - Link to Github issues related to fixing the issues
2. A wiki page with a manual testing checklist that folks can run through

**Comment by willmot** [comment]
@owaincuvelier would love your feedback  / help on this.

**Comment by owaincuvelier** [comment]
@willmot so need to think about this a bit. My initial thought would be that we add a footer to our support emails and maybe have a survey link people can take so we can get details about who the host is, what plan they're on, ect. In addition to the default footer, I'd also 'up sell' the survey on tickets I think valuable to get server details.

Then we can pipe this into the spreadsheet and aggregate the data. We can also kick things off with an intercom blast.

**Comment by willmot** [comment]
@owaincuvelier sounds cool 👍

As a first step, lets:

- [ ] Create the Spreadsheet
- [ ] Seed it with some initial data about hosts we have access to / know about
- [ ] Create a wiki page to document how to go about testing if your host works and updating the Spreadsheet with your findings

**Comment by owaincuvelier** [comment]
Need to find a good service for simple & beautiful surveys. 

https://docs.google.com/spreadsheets/d/19hFRF6omWb2GrlkZrQ_dEUqdESu9wMGqbiDc6te9zIM/edit#gid=0

wiki page will be here: https://github.com/humanmade/backupwordpress/wiki/Functionality-Checklist

**Comment by pdewouters** [comment]
off the top of my head

- polldaddy
- surveymonkey
- gravity forms has a poll addon I think - could integrate into bwp.hmn.md

**Comment by willmot** [comment]
@owaincuvelier to start with I'd just expect people to contribute directly to the spreadsheet as a public resource.

We can refer to it directly in our documentation (here's a list of known issues with hosts etc) and can ask people to add theirs if it's not there.

- [ ] We should also add a note about it to our contributing.md file
